---
title: "Resume"

---
**Jacob Cathcart**

335 Old Bristol Road Apt. 301 - Boone, NC 28607 - Cathcartjk@appstate.edu - 919-800-8208

**EDUCATION**

**Appalachian State University, Boone, NC**                                                                     _Expected Graduation: Dec. 2018_

_Bachelor of Science in Mathematics_

_Minor in Physics_

**EMPLOYMENT HISTORY**

**Camp Sea Gull                                                                                          ** _May 2013- August 2016 (Summers)_

_Lightning and Flying Scot Sailing UA_

- Responsible for the safety of all campers, staff and equipment.
- Communicated daily with counterparts to keep team informed and troubleshoot problems.

- Supervised all aspects of the Lightning and Flying Scot programs.
- Scheduled, resourced and mentored Flying Scot and Lightning staff and candidates.
- Engaged trainers in creating lesson plans for four- and two-week sailing programs.
- Supervised Flying Scot and Lightning trainers and fleet captains.
- Assessed staff qualifications and allocated staff accordingly.
- Set high expectations for teaching and communicating information.  Train staff and hold them accountable through regular feedback and formal evaluations.

**Jersey Mikes Subs**

_Shift Manager                                                                                                  August 2015- January 2016_

- Responsible for opening and closing the store.
- Trained new crew members.
- Responsible for counting the money drawer at the end of each day.
- Ensured a positive experience for the customers through superior customer service.

**Appalachian State University Physics Department**

_Lab Technician                _                                                                                                    _April 2016 – October 2016_

**Our Daily Bread**

_Kitchen Staff_

- Learned how to effectively multitask and manage time in the most efficient way possible



EXTRACURRICULAR ACTIVITIES 

**Pi Kappa Alpha Social Fraternity, Appalachian State University, Boone, NC                           ** _January 2016-Present_

**Member**

 **Philanthropy Chair**                                                                                                                                        _January 2017- Present_

- Planned and coordinated several fundraising events
- Directly oversaw the collection and donation of raised for local and national charities

**Panda (Physics and Astronomy) Club General Member                                                                      ** _January 2017-Present_                

**Math Club General Member                       ** _January 2017-Present_



**Skills and Achievements**

- Proficient in Microsoft office     
- Diligent worker                  
- Experienced in Adobe Photoshop     
- Computer programing skills in R and Python
- Experienced in Adobe InDesign      
- Excellent communication skills     
- Exceptional problem solving abilities
- **Publication** - Co-author J. Cathcart, Et Al. &quot;Combining Fuzzy-AHP and Borda Counting to Select a Candidate,&quot; INFORMS Business Analytics Conference, Las Vegas, January 2017. URL: http://mathsci.appstate.edu/∼wmcb/INFORMS/2017/Candidate Selection.pdf